version: '3.8'

services:
  canteenx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canteenx_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=canteenx_prod_secret_2026_super_secure
    volumes:
      - sqlite_data:/app/backend/database.sqlite
    restart: unless-stopped

volumes:
  sqlite_data:
